# Generated by Django 2.1.1 on 2018-09-27 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='kettle_job_config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=128)),
                ('step_type', models.CharField(max_length=8)),
                ('exec_type', models.IntegerField()),
                ('exec_time_interval', models.IntegerField()),
                ('exec_time_begin', models.DateTimeField()),
                ('exec_time_end', models.DateTimeField()),
                ('vaild_flag', models.IntegerField()),
                ('create_time', models.DateTimeField()),
                ('update_time', models.DateTimeField()),
                ('remark', models.CharField(max_length=255)),
            ],
        ),
    ]
